---
name: Lint Ansible code
description: Run ansible-lint on some ansible role, playbook, etc.
author: pako-23 <pasqualepolverino98@gmail.com>
branding:
  icon: shield
  color: blue
inputs: {}
# TODO add a mapping of outputs for the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#outputs-for-composite-actions
outputs: {}
runs:
  using: composite
  # TODO add steps describing what the action should do.
  # https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runssteps
  steps:
    - name:
      shell: bash
      run: echo TODO add steps
